spring:
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  datasource:
    username: root
    password: Pandesal123
    url: jdbc:mysql://localhost/gymmembership
    driverClassName: com.mysql.cj.jdbc.Driver