spring:
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  datasource:
    username: ${DB_USER}
    password: ${DB_PASS}
    url: jdbc:mysql://${DB_HOST}/${DB_NAME}
    driverClassName: com.mysql.cj.jdbc.Driver
  profiles:
    active: ${SPRING_PROFILES_ACTIVE}
  application:
    name: gym-membership-application

server:
  port: ${SERVER_PORT}
  servlet:
    context-path: ${SERVER_CONTEXT_PATH}